language: python

python:
  "3.6"

install:
 - pip install -r requirements.txt 
 - pip install coveralls codecov
 - pip install codeclimate-test-reporter

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
 - pytest --cov-report=term-missing --cov=app

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
 - coveralls 
 - codecov --token=Im6bhD79ZFujhndQFTVjOT8D60Zd1caj1
 - codeclimate-test-reporter